package unit

import (
	"github.com/funtimecoding/soil/pkg/assert"
	"github.com/funtimecoding/soil/pkg/lint"
	"github.com/funtimecoding/soil/pkg/lint/concern"
	"github.com/funtimecoding/soil/pkg/lint/constant"
	"github.com/funtimecoding/soil/pkg/lint/option"
	"github.com/funtimecoding/soil/pkg/lint/output"
	"github.com/funtimecoding/soil/pkg/system/virtual_file_system"
	"testing"
)

func TestCheckImportFix(t *testing.T) {
	v := virtual_file_system.New()
	v.WriteString(
		"pkg/foo/foo.go",
		"package foo\n\nimport (\n\t\"fmt\"\n)\n\nfunc Foo() {\n\tfmt.Println(\"hello\")\n}\n",
	)
	var r output.Results
	fixes := lint.Check(v, option.New("", false), false, false, &r)
	assert.String(
		t,
		"package foo\n\nimport \"fmt\"\n\nfunc Foo() {\n\tfmt.Println(\"hello\")\n}\n",
		fixes.ReadString("pkg/foo/foo.go"),
	)
}

func TestCheckCleanNoFixes(t *testing.T) {
	v := virtual_file_system.New()
	v.WriteString(
		"pkg/foo/foo.go",
		"package foo\n\nimport \"fmt\"\n\nfunc Foo() {\n\tfmt.Println(\"hello\")\n}\n",
	)
	v.WriteString(
		"pkg/foo/foo_test.go",
		"package foo\n\nimport \"testing\"\n\nfunc TestFoo(t *testing.T) {\n\tt.Parallel()\n}\n",
	)
	var r output.Results
	fixes := lint.Check(v, option.New("", false), false, false, &r)
	assert.Boolean(t, false, fixes.Has("pkg/foo/foo.go"))
	assert.Boolean(t, false, fixes.Has("pkg/foo/foo_test.go"))
}

func TestCheckSkipsGeneratedFile(t *testing.T) {
	v := virtual_file_system.New()
	v.WriteString(
		"pkg/foo/generated.go",
		"package foo\n\nimport (\n\t\"fmt\"\n)\n\nfunc Generated() {\n\tfmt.Println(\"hello\")\n}\n",
	)
	var r output.Results
	fixes := lint.Check(v, option.New("", false), false, false, &r)
	assert.Boolean(t, false, fixes.Has("pkg/foo/generated.go"))
}

func TestCheckSkipsGeneratedHeader(t *testing.T) {
	v := virtual_file_system.New()
	v.WriteString(
		"pkg/foo/service.pb.go",
		"// Code generated by protoc-gen-go. DO NOT EDIT.\npackage foo\n\nimport (\n\t\"fmt\"\n)\n\nfunc Generated() {\n\tfmt.Println(\"hello\")\n}\n",
	)
	var r output.Results
	fixes := lint.Check(v, option.New("", false), false, false, &r)
	assert.Boolean(t, false, fixes.Has("pkg/foo/service.pb.go"))
	assert.Integer(t, 0, len(r.Entries))
}

func TestCheckSkipsGeneratedHeaderLineThree(t *testing.T) {
	v := virtual_file_system.New()
	v.WriteString(
		"pkg/foo/server.go",
		"// Package foo provides primitives.\n//\n// Code generated by oapi-codegen. DO NOT EDIT.\npackage foo\n\nimport (\n\t\"fmt\"\n)\n\nfunc Generated() {\n\tfmt.Println(\"hello\")\n}\n",
	)
	var r output.Results
	fixes := lint.Check(v, option.New("", false), false, false, &r)
	assert.Boolean(t, false, fixes.Has("pkg/foo/server.go"))
	assert.Integer(t, 0, len(r.Entries))
}

func TestCheckDoesNotSkipNormalFile(t *testing.T) {
	v := virtual_file_system.New()
	v.WriteString(
		"pkg/foo/foo.go",
		"package foo\n\nimport (\n\t\"fmt\"\n)\n\nfunc Foo() {\n\tfmt.Println(\"hello\")\n}\n",
	)
	var r output.Results
	fixes := lint.Check(v, option.New("", false), false, false, &r)
	assert.Boolean(t, true, fixes.Has("pkg/foo/foo.go"))
}

func TestCheckVariableFlaggedNoFix(t *testing.T) {
	v := virtual_file_system.New()
	v.WriteString(
		"pkg/foo/foo.go",
		"package foo\n\nimport \"fmt\"\n\nfunc Foo() {\n\terr := fmt.Errorf(\"oops\")\n\t_ = err\n}\n",
	)
	v.WriteString(
		"pkg/foo/foo_test.go",
		"package foo\n\nimport \"testing\"\n\nfunc TestFoo(t *testing.T) {\n}\n",
	)
	var r output.Results
	fixes := lint.Check(v, option.New("", false), false, false, &r)
	assert.Boolean(t, false, fixes.Has("pkg/foo/foo.go"))
}

func TestCheckMultipleFilesOnlyBrokenFixed(t *testing.T) {
	v := virtual_file_system.New()
	v.WriteString(
		"pkg/foo/foo.go",
		"package foo\n\nimport (\n\t\"fmt\"\n)\n\nfunc Foo() {\n\tfmt.Println(\"hello\")\n}\n",
	)
	v.WriteString(
		"pkg/foo/bar.go",
		"package foo\n\nimport \"fmt\"\n\nfunc Bar() {\n\tfmt.Println(\"world\")\n}\n",
	)
	v.WriteString(
		"pkg/foo/foo_test.go",
		"package foo\n\nimport \"testing\"\n\nfunc TestFoo(t *testing.T) {\n}\n",
	)
	var r output.Results
	fixes := lint.Check(v, option.New("", false), false, false, &r)
	assert.Boolean(t, true, fixes.Has("pkg/foo/foo.go"))
	assert.Boolean(t, false, fixes.Has("pkg/foo/bar.go"))
}

func TestCheckResultImportCollapsed(t *testing.T) {
	v := virtual_file_system.New()
	v.WriteString(
		"pkg/foo/foo.go",
		"package foo\n\nimport (\n\t\"fmt\"\n)\n\nfunc Foo() {\n\tfmt.Println(\"hello\")\n}\n",
	)
	var r output.Results
	lint.Check(v, option.New("", false), true, false, &r)
	assertApplied(
		t,
		r.Entries,
		"pkg/foo/foo.go",
		constant.SingleMultiImportText,
	)
}

func TestCheckResultBlankLineRemoved(t *testing.T) {
	v := virtual_file_system.New()
	v.WriteString(
		"pkg/foo/foo.go",
		"package foo\n\nfunc Foo() {\n\ta := 1\n\n\t_ = a\n}\n",
	)
	var r output.Results
	lint.Check(v, option.New("", false), true, false, &r)
	assertApplied(
		t,
		r.Entries,
		"pkg/foo/foo.go",
		constant.BlankInsideFunctionText,
	)
}

func TestCheckResultBlankLineInserted(t *testing.T) {
	v := virtual_file_system.New()
	v.WriteString(
		"pkg/foo/foo.go",
		"package foo\n\nfunc Foo() {\n\ta := 1\n\tif a > 0 {\n\t\t_ = a\n\t}\n}\n",
	)
	var r output.Results
	lint.Check(v, option.New("", false), true, false, &r)
	assertApplied(
		t,
		r.Entries,
		"pkg/foo/foo.go",
		constant.MissingBlankBeforeControlText,
	)
}

func assertApplied(
	t *testing.T,
	entries []*concern.Concern,
	path string,
	message string,
) {
	t.Helper()

	for _, c := range entries {
		if c.Path == path && c.Text == message && c.Fixed {
			return
		}
	}

	t.Errorf(
		"expected applied concern {path: %q, text: %q} not found",
		path,
		message,
	)
}
