package unit

import (
	"github.com/funtimecoding/soil/pkg/assert"
	"github.com/funtimecoding/soil/pkg/constant"
	"github.com/funtimecoding/soil/pkg/lint"
	"github.com/funtimecoding/soil/pkg/lint/unit/lint_tester"
	"path/filepath"
	"testing"
)

func TestIsGeneratedFileProtoc(t *testing.T) {
	path := lint_tester.WriteTestFile(
		t,
		"service.pb.go",
		"// Code generated by protoc-gen-go. DO NOT EDIT.\npackage foo\n",
	)
	assert.True(t, lint.IsGeneratedFile(path))
}

func TestIsGeneratedFileOapiCodegen(t *testing.T) {
	path := lint_tester.WriteTestFile(
		t,
		constant.GeneratedFile,
		"// Package client provides primitives.\n//\n// Code generated by oapi-codegen. DO NOT EDIT.\npackage client\n",
	)
	assert.True(t, lint.IsGeneratedFile(path))
}

func TestIsGeneratedFileNormal(t *testing.T) {
	path := lint_tester.WriteTestFile(
		t,
		"foo.go",
		"package foo\n\nfunc Foo() {}\n",
	)
	assert.Boolean(t, false, lint.IsGeneratedFile(path))
}

func TestIsGeneratedFileNotFound(t *testing.T) {
	assert.Boolean(
		t,
		false,
		lint.IsGeneratedFile(filepath.Join(t.TempDir(), "missing.go")),
	)
}
