package packager

import (
	"fmt"
	"github.com/funtimecoding/soil/pkg/alpine/constant"
	"time"
)

func renderPKGINFO(
	pkgname string,
	pkgver string,
	size int64,
	datahash string,
) string {
	return fmt.Sprintf(
		"# Generated by gopackageapk\npkgname = %s\npkgver = %s\npkgdesc = %s\nurl = https://example.com\nbuilddate = %d\nsize = %d\narch = %s\ndatahash = %s\n",
		pkgname,
		pkgver,
		pkgname,
		time.Now().Unix(),
		size,
		constant.Architecture,
		datahash,
	)
}
