package integration

import (
	"github.com/funtimecoding/soil/pkg/lint/analyzer/testutil"
	"testing"
)

func module(t *testing.T) string {
	t.Helper()
	root := t.TempDir()
	testutil.WriteModFile(t, root, "example.test/m")
	testutil.WriteFile(
		t,
		root,
		"pkg/a/covered.go",
		`package a

func Covered(a bool) int {
	if a {
		return 1
	}

	return 2
}
`,
	)
	testutil.WriteFile(
		t,
		root,
		"pkg/a/half.go",
		`package a

func Half(a int) int {
	if a > 0 {
		return 1
	}

	return 2
}
`,
	)
	testutil.WriteFile(
		t,
		root,
		"pkg/a/generated.go",
		"// Code generated by tool. DO NOT EDIT.\n\npackage a\n\nfunc Generated() {}\n",
	)
	testutil.WriteFile(
		t,
		root,
		"pkg/a/thing.go",
		`package a

type Thing struct{}

func (t *Thing) Untested(a, b bool) bool {
	if a && b {
		return true
	}

	return false
}
`,
	)
	testutil.WriteFile(
		t,
		root,
		"pkg/a/unit/a_test.go",
		`package unit

import (
	"example.test/m/pkg/a"
	"testing"
)

func TestCovered(t *testing.T) {
	a.Covered(true)
	a.Covered(false)
	a.Half(1)
}
`,
	)

	return root
}
