package unit_test

import (
	"github.com/funtimecoding/soil/pkg/assert"
	"github.com/funtimecoding/soil/pkg/prometheus/alertmanager/constant"
	"testing"
)

func TestAlertmanagerConstantAlert(t *testing.T) {
	assert.String(t, "AddressPool", constant.AddressPool)
	assert.String(t, "Backup", constant.Backup)
	assert.String(t, "Battery", constant.Battery)
	assert.String(t, "Bucket", constant.Bucket)
	assert.String(t, "Cache", constant.Cache)
	assert.String(t, "Certificate", constant.Certificate)
	assert.String(t, "Check", constant.Check)
	assert.String(t, "Clock", constant.Clock)
	assert.String(t, "Cluster", constant.Cluster)
	assert.String(t, "Configuration", constant.Configuration)
	assert.String(t, "Connection", constant.Connection)
	assert.String(t, "Container", constant.Container)
	assert.String(t, "Controller", constant.Controller)
	assert.String(t, "DaemonSet", constant.DaemonSet)
	assert.String(t, "Database", constant.Database)
	assert.String(t, "Date", constant.Date)
	assert.String(t, "Deadline", constant.Deadline)
	assert.String(t, "Deployment", constant.Deployment)
	assert.String(t, "Disk", constant.Disk)
	assert.String(t, "Event", constant.Event)
	assert.String(t, "Fan", constant.Fan)
	assert.String(t, "Forward", constant.Forward)
	assert.String(t, "Hardware", constant.Hardware)
	assert.String(t, "Interface", constant.Interface)
	assert.String(t, "Label", constant.Label)
	assert.String(t, "Latency", constant.Latency)
	assert.String(t, "Limit", constant.Limit)
	assert.String(t, "Measure", constant.Measure)
	assert.String(t, "Message", constant.Message)
	assert.String(t, "MountPoint", constant.MountPoint)
	assert.String(t, "Network", constant.Network)
	assert.String(t, "Node", constant.Node)
	assert.String(t, "Person", constant.Person)
	assert.String(t, "Pod", constant.Pod)
	assert.String(t, "PowerSupply", constant.PowerSupply)
	assert.String(t, "Processor", constant.Processor)
	assert.String(t, "Queue", constant.Queue)
	assert.String(t, "Rack", constant.Rack)
	assert.String(t, "ReplicaSet", constant.ReplicaSet)
	assert.String(t, "Replication", constant.Replication)
	assert.String(t, "Report", constant.Report)
	assert.String(t, "Secret", constant.Secret)
	assert.String(t, "Service", constant.Service)
	assert.String(t, "StatefulSet", constant.StatefulSet)
	assert.String(t, "System", constant.System)
	assert.String(t, "Temperature", constant.Temperature)
	assert.String(t, "Token", constant.Token)
	assert.String(t, "Volume", constant.Volume)
	assert.String(t, "Bad", constant.Bad)
	assert.String(t, "Behind", constant.Behind)
	assert.String(t, "Big", constant.Big)
	assert.String(t, "Broken", constant.Broken)
	assert.String(t, "Close", constant.Close)
	assert.String(t, "Corrupt", constant.Corrupt)
	assert.String(t, "Crashed", constant.Crashed)
	assert.String(t, "Degraded", constant.Degraded)
	assert.String(t, "Disconnected", constant.Disconnected)
	assert.String(t, "Down", constant.Down)
	assert.String(t, "Empty", constant.Empty)
	assert.String(t, "Exceeded", constant.Exceeded)
	assert.String(t, "Expired", constant.Expired)
	assert.String(t, "Frozen", constant.Frozen)
	assert.String(t, "Full", constant.Full)
	assert.String(t, "Hot", constant.Hot)
	assert.String(t, "Imbalance", constant.Imbalance)
	assert.String(t, "Inconsistent", constant.Inconsistent)
	assert.String(t, "Lag", constant.Lag)
	assert.String(t, "Load", constant.Load)
	assert.String(t, "Logon", constant.Logon)
	assert.String(t, "Low", constant.Low)
	assert.String(t, "Missing", constant.Missing)
	assert.String(t, "NearBroken", constant.NearBroken)
	assert.String(t, "NearExceeded", constant.NearExceeded)
	assert.String(t, "NearExpired", constant.NearExpired)
	assert.String(t, "NearFull", constant.NearFull)
	assert.String(t, "Off", constant.Off)
	assert.String(t, "Old", constant.Old)
	assert.String(t, "OutOfMemory", constant.OutOfMemory)
	assert.String(t, "OutOfSync", constant.OutOfSync)
	assert.String(t, "Overload", constant.Overload)
	assert.String(t, "ReadOnly", constant.ReadOnly)
	assert.String(t, "Received", constant.Received)
	assert.String(t, "Saturated", constant.Saturated)
	assert.String(t, "Set", constant.Set)
	assert.String(t, "Slow", constant.Slow)
	assert.String(t, "Stuck", constant.Stuck)
	assert.String(t, "Timeout", constant.Timeout)
	assert.String(t, "Unbound", constant.Unbound)
	assert.String(t, "Unhealthy", constant.Unhealthy)
	assert.String(t, "Okay", constant.Okay)
}
