package unit

import (
	"github.com/funtimecoding/soil/pkg/assert"
	"github.com/funtimecoding/soil/pkg/constant"
	"github.com/funtimecoding/soil/pkg/measure"
	"github.com/funtimecoding/soil/pkg/measure/option"
	"github.com/funtimecoding/soil/pkg/measure/registry"
	"path/filepath"
	"testing"
)

func TestScan(t *testing.T) {
	root := t.TempDir()
	write(
		root,
		constant.MainFile,
		"package main\n\n// comment\nfunc main() {}\n",
	)
	write(
		root,
		"main_test.go",
		"package main\n\nfunc TestMain(t *testing.T) {}\n",
	)
	write(
		root,
		constant.GeneratedFile,
		"// Code generated by tool. DO NOT EDIT.\n\npackage main\n",
	)
	write(root, "vendor/dep.go", "package dep\n")
	write(root, ".git/config", "[core]\n")
	write(root, "doc/README.md", "# Title\n\ntext\n")
	write(root, "bin/blob.unknown", "?\n")
	write(root, "skipme/inner.go", "package inner\n")
	o := option.New()
	o.Paths = []string{root}
	o.Skips = []string{"skipme"}
	r := measure.Scan(o, registry.NewDefault())
	assert.Count(t, 3, r.Files)
	assert.Strings(
		t,
		[]string{filepath.Join(root, "bin/blob.unknown")},
		r.Unplaced,
	)
	v := r.ByLanguage()
	assert.Count(t, 3, v)
	assert.String(t, "Go", v[0].Language)
	assert.Integer(t, 2, v[0].Count.Code)
	assert.Integer(t, 1, v[0].Count.Comment)
	assert.Integer(t, 1, v[0].Count.Blank)
	assert.String(t, "Go Test", v[1].Language)
	assert.Integer(t, 2, v[1].Count.Code)
	assert.String(t, "Markdown", v[2].Language)
	assert.Integer(t, 2, v[2].Count.Code)
}
