FROM debian:13.6-slim
RUN apt-get update && apt-get install -y --no-install-recommends libsqlite3-0 && rm -rf /var/lib/apt/lists/*
COPY tmp/gocertificated/linux-amd64/gocertificated /usr/local/bin
ENTRYPOINT ["gocertificated"]
