package constant

const (
	BooleanFalse = "0"
	BooleanTrue  = "1"
	Zero         = "0"
	One          = "1"
	Two          = "2"
	Three        = "3"
	Four         = "4"
	Five         = "5"
	Digits       = "0123456789"

	CapitalAlfa  = "ALFA"
	CapitalBravo = "BRAVO"

	LowerAlfa    = "alfa"
	LowerBravo   = "bravo"
	LowerCharlie = "charlie"
	LowerDelta   = "delta"

	UpperAlfa    = "Alfa"
	UpperBravo   = "Bravo"
	UpperCharlie = "Charlie"
	UpperDelta   = "Delta"
	UpperEcho    = "Echo"
	UpperFoxtrot = "Foxtrot"
	UpperGolf    = "Golf"
	UpperHotel   = "Hotel"
	UpperIndia   = "India"
	UpperJuliett = "Juliett"
	UpperKilo    = "Kilo"
	UpperLima    = "Lima"
	UpperMike    = "Mike"

	Ampersand      = "&"
	At             = "@"
	Colon          = ":"
	Comma          = ","
	CommaSpace     = ", "
	Dash           = "-"
	Dot            = "."
	DoubleColon    = "::"
	DoubleSlash    = "//"
	DoubleSpace    = "  "
	Equals         = "="
	Hash           = "#"
	Pipe           = "|"
	Plus           = "+"
	Question       = "?"
	Semicolon      = ";"
	SemicolonSpace = "; "
	Slash          = "/"
	Space          = " "
	SpacedMiddot   = " · "
	Tab            = "\t"
	Underscore     = "_"
	Unix           = "\n"
)
