package constant

const (
	Ampersand      = "&"
	At             = "@"
	Colon          = ":"
	Comma          = ","
	CommaSpace     = ", "
	Dash           = "-"
	Dot            = "."
	DoubleColon    = "::"
	DoubleSlash    = "//"
	DoubleSpace    = "  "
	Equals         = "="
	Hash           = "#"
	Pipe           = "|"
	Plus           = "+"
	Question       = "?"
	Semicolon      = ";"
	SemicolonSpace = "; "
	Slash          = "/"
	Space          = " "
	Tab            = "\t"
	Underscore     = "_"
	Unix           = "\n"
)
