package unit

import (
	"github.com/funtimecoding/soil/pkg/assert"
	"github.com/funtimecoding/soil/pkg/prometheus/constant"
	"testing"
)

func TestAlertmanagerConstantAlert(t *testing.T) {
	assert.String(t, "AddressPool", constant.EntityAddressPool)
	assert.String(t, "Backup", constant.EntityBackup)
	assert.String(t, "Battery", constant.EntityBattery)
	assert.String(t, "Bucket", constant.EntityBucket)
	assert.String(t, "Cache", constant.EntityCache)
	assert.String(t, "Certificate", constant.EntityCertificate)
	assert.String(t, "Check", constant.EntityCheck)
	assert.String(t, "Clock", constant.EntityClock)
	assert.String(t, "Cluster", constant.EntityCluster)
	assert.String(t, "Configuration", constant.EntityConfiguration)
	assert.String(t, "Connection", constant.EntityConnection)
	assert.String(t, "Container", constant.EntityContainer)
	assert.String(t, "Controller", constant.EntityController)
	assert.String(t, "DaemonSet", constant.EntityDaemonSet)
	assert.String(t, "Database", constant.EntityDatabase)
	assert.String(t, "Date", constant.EntityDate)
	assert.String(t, "Deadline", constant.EntityDeadline)
	assert.String(t, "Deployment", constant.EntityDeployment)
	assert.String(t, "Disk", constant.EntityDisk)
	assert.String(t, "Event", constant.EntityEvent)
	assert.String(t, "Fan", constant.EntityFan)
	assert.String(t, "Forward", constant.EntityForward)
	assert.String(t, "Hardware", constant.EntityHardware)
	assert.String(t, "Interface", constant.EntityInterface)
	assert.String(t, "Label", constant.EntityLabel)
	assert.String(t, "Latency", constant.EntityLatency)
	assert.String(t, "Limit", constant.EntityLimit)
	assert.String(t, "Measure", constant.EntityMeasure)
	assert.String(t, "Message", constant.EntityMessage)
	assert.String(t, "MountPoint", constant.EntityMountPoint)
	assert.String(t, "Network", constant.EntityNetwork)
	assert.String(t, "Node", constant.EntityNode)
	assert.String(t, "Person", constant.EntityPerson)
	assert.String(t, "Pod", constant.EntityPod)
	assert.String(t, "PowerSupply", constant.EntityPowerSupply)
	assert.String(t, "Processor", constant.EntityProcessor)
	assert.String(t, "Queue", constant.EntityQueue)
	assert.String(t, "Rack", constant.EntityRack)
	assert.String(t, "ReplicaSet", constant.EntityReplicaSet)
	assert.String(t, "Replication", constant.EntityReplication)
	assert.String(t, "Report", constant.EntityReport)
	assert.String(t, "Secret", constant.EntitySecret)
	assert.String(t, "Service", constant.EntityService)
	assert.String(t, "StatefulSet", constant.EntityStatefulSet)
	assert.String(t, "System", constant.EntitySystem)
	assert.String(t, "Temperature", constant.EntityTemperature)
	assert.String(t, "Token", constant.EntityToken)
	assert.String(t, "Volume", constant.EntityVolume)
	assert.String(t, "Bad", constant.CategoryBad)
	assert.String(t, "Behind", constant.CategoryBehind)
	assert.String(t, "Big", constant.CategoryBig)
	assert.String(t, "Broken", constant.CategoryBroken)
	assert.String(t, "Close", constant.CategoryClose)
	assert.String(t, "Corrupt", constant.CategoryCorrupt)
	assert.String(t, "Crashed", constant.CategoryCrashed)
	assert.String(t, "Degraded", constant.CategoryDegraded)
	assert.String(t, "Disconnected", constant.CategoryDisconnected)
	assert.String(t, "Down", constant.CategoryDown)
	assert.String(t, "Empty", constant.CategoryEmpty)
	assert.String(t, "Exceeded", constant.CategoryExceeded)
	assert.String(t, "Expired", constant.CategoryExpired)
	assert.String(t, "Frozen", constant.CategoryFrozen)
	assert.String(t, "Full", constant.CategoryFull)
	assert.String(t, "Hot", constant.CategoryHot)
	assert.String(t, "Imbalance", constant.CategoryImbalance)
	assert.String(t, "Inconsistent", constant.CategoryInconsistent)
	assert.String(t, "Lag", constant.CategoryLag)
	assert.String(t, "Load", constant.CategoryLoad)
	assert.String(t, "Logon", constant.CategoryLogon)
	assert.String(t, "Low", constant.CategoryLow)
	assert.String(t, "Missing", constant.CategoryMissing)
	assert.String(t, "NearBroken", constant.CategoryNearBroken)
	assert.String(t, "NearExceeded", constant.CategoryNearExceeded)
	assert.String(t, "NearExpired", constant.CategoryNearExpired)
	assert.String(t, "NearFull", constant.CategoryNearFull)
	assert.String(t, "Off", constant.CategoryOff)
	assert.String(t, "Old", constant.CategoryOld)
	assert.String(t, "OutOfMemory", constant.CategoryOutOfMemory)
	assert.String(t, "OutOfSync", constant.CategoryOutOfSync)
	assert.String(t, "Overload", constant.CategoryOverload)
	assert.String(t, "ReadOnly", constant.CategoryReadOnly)
	assert.String(t, "Received", constant.CategoryReceived)
	assert.String(t, "Saturated", constant.CategorySaturated)
	assert.String(t, "Set", constant.CategorySet)
	assert.String(t, "Slow", constant.CategorySlow)
	assert.String(t, "Stuck", constant.CategoryStuck)
	assert.String(t, "Timeout", constant.CategoryTimeout)
	assert.String(t, "Unbound", constant.CategoryUnbound)
	assert.String(t, "Unhealthy", constant.CategoryUnhealthy)
	assert.String(t, "Okay", constant.CategoryOkay)
}
