package unit_test

import (
	"github.com/funtimecoding/soil/pkg/argument"
	"github.com/funtimecoding/soil/pkg/assert"
	"testing"
)

func TestConstant(t *testing.T) {
	assert.String(t, "arm", argument.Arm)
	assert.String(t, "bulk", argument.Bulk)
	assert.String(t, "cluster", argument.Cluster)
	assert.String(t, "container", argument.Container)
	assert.String(t, "context", argument.Context)
	assert.String(t, "core", argument.Core)
	assert.String(t, "dense", argument.Dense)
	assert.String(t, "disk", argument.Disk)
	assert.String(t, "download", argument.Download)
	assert.String(t, "end", argument.End)
	assert.String(t, "file", argument.File)
	assert.String(t, "group", argument.Group)
	assert.String(t, "hardware", argument.Hardware)
	assert.String(t, "information", argument.Information)
	assert.String(t, "interactive", argument.Interactive)
	assert.String(t, "investigate", argument.Investigate)
	assert.String(t, "issue", argument.Issue)
	assert.String(t, "key", argument.Key)
	assert.String(t, "log", argument.Log)
	assert.String(t, "loop", argument.Loop)
	assert.String(t, "maintainer-mail", argument.MaintainerMail)
	assert.String(t, "maintainer-name", argument.MaintainerName)
	assert.String(t, "memory", argument.Memory)
	assert.String(t, "message", argument.Message)
	assert.String(t, "migrate", argument.Migrate)
	assert.String(t, "mine", argument.Mine)
	assert.String(t, "name", argument.Name)
	assert.String(t, "node", argument.Node)
	assert.String(t, "old", argument.Old)
	assert.String(t, "package", argument.Package)
	assert.String(t, "parent", argument.Parent)
	assert.String(t, "password", argument.Password)
	assert.String(t, "pod", argument.Pod)
	assert.String(t, "pretend", argument.Pretend)
	assert.String(t, "reset", argument.Reset)
	assert.String(t, "retry", argument.Retry)
	assert.String(t, "run", argument.Run)
	assert.String(t, "runbook", argument.Runbook)
	assert.String(t, "schedule", argument.Schedule)
	assert.String(t, "source", argument.Source)
	assert.String(t, "space", argument.Space)
	assert.String(t, "statistic", argument.Statistic)
	assert.String(t, "summary", argument.Summary)
	assert.String(t, "systemd-unit", argument.SystemdUnit)
	assert.String(t, "team", argument.Team)
	assert.String(t, "title", argument.Title)
	assert.String(t, "topic", argument.Topic)
	assert.String(t, "unknown", argument.Unknown)
}
