package module_tester

import "testing"

func Fix(t *testing.T) string {
	t.Helper()

	return New(t, "testmodule").
		File(
			"pkg/types/directory_path.go",
			"package types\n\nfunc DirPath() string { return dirName }\n",
		).
		File(
			"pkg/types/directory_name.go",
			"package types\n\nvar dirName = \"test\"\n",
		).
		File(
			"pkg/types/stray_const.go",
			"package types\n\nconst StrayConst = \"value\"\n",
		).
		File(
			"pkg/types/generated.go",
			"package types\n\n// Code generated by tool DO NOT EDIT.\n\ntype ParamError struct{}\n",
		).
		File(
			"pkg/face/worker.go",
			"package face\n\ntype Worker interface {\n\tAddr() string\n}\n",
		).
		File(
			"pkg/impl/impl.go",
			"package impl\n\nimport \"testmodule/pkg/face\"\n\ntype Server struct{}\n\nfunc (s Server) Addr() string { return \"\" }\n\nvar _ face.Worker = Server{}\n",
		).
		File(
			"pkg/consumer/use.go",
			"package consumer\n\nimport \"testmodule/pkg/types\"\n\nfunc Example() string {\n\t_ = types.StrayConst\n\n\treturn types.DirPath()\n}\n",
		).
		File(
			"pkg/fields/entry.go",
			"package fields\n\ntype Entry struct {\n\tRef string\n}\n",
		).
		File(
			"pkg/multi/example.go",
			"package multi\n\nfunc Example() string {\n\tfooRef := \"x\"\n\n\treturn fooRef\n}\n",
		).
		File(
			"pkg/collision/example.go",
			"package collision\n\nfunc Example() string {\n\tr := \"taken\"\n\tref := \"test\"\n\n\treturn r + ref\n}\n",
		).
		File(
			"pkg/abort/example.go",
			"package abort\n\nfunc Example() string {\n\tt := \"taken\"\n\ttx := \"test\"\n\n\treturn t + tx\n}\n",
		).
		File(
			"pkg/shadow/example.go",
			"package shadow\n\nfunc Example() string {\n\tm := map[string]string{\"k\": \"x\"}\n\n\tfor _, val := range m {\n\t\tv := val\n\t\t_ = v\n\t}\n\n\treturn \"\"\n}\n",
		).
		File(
			"pkg/parent/example.go",
			"package parent\n\nfunc Example() {\n\ts := \"status\"\n\tsources := []string{\"a\"}\n\n\tfor _, src := range sources {\n\t\t_ = s + src\n\t}\n}\n",
		).
		File(
			"pkg/sentinel/sentinel.go",
			"package sentinel\n\nimport \"fmt\"\n\nvar ErrQuit = fmt.Errorf(\"quit\")\n",
		).
		File(
			"pkg/caller/caller.go",
			"package caller\n\nimport (\n\t\"errors\"\n\t\"testmodule/pkg/sentinel\"\n)\n\nfunc Check(e error) bool {\n\treturn errors.Is(e, sentinel.ErrQuit)\n}\n",
		).
		File(
			"pkg/tagged/tagged.go",
			"//go:build ignore\n\npackage tagged\n\nimport (\n\t\"errors\"\n\t\"testmodule/pkg/sentinel\"\n)\n\nfunc Handle(e error) bool {\n\treturn errors.Is(e, sentinel.ErrQuit)\n}\n",
		).
		File(
			"pkg/errs/example.go",
			"package errs\n\nimport \"fmt\"\n\nfunc Example() {\n\te := fmt.Errorf(\"first\")\n\terr := fmt.Errorf(\"second\")\n\t_ = e\n\t_ = err\n}\n",
		).
		File(
			"pkg/errs/triple.go",
			"package errs\n\nimport \"fmt\"\n\nfunc Triple() {\n\te := fmt.Errorf(\"first\")\n\tf := fmt.Errorf(\"second\")\n\terr := fmt.Errorf(\"third\")\n\t_ = e\n\t_ = f\n\t_ = err\n}\n",
		).
		Directory()
}
