package module_tester

import (
	"github.com/funtimecoding/soil/pkg/constant"
	"testing"
)

func ImportAlias(t *testing.T) string {
	t.Helper()

	return New(t, "testmodule").
		File(
			"pkg/helper/helper.go",
			"package helper\n\nfunc Value() string { return \"hello\" }\n",
		).
		File(
			"pkg/other/helper/helper.go",
			"package helper\n\nfunc Extra() string { return \"extra\" }\n",
		).
		File(
			"pkg/util-stuff/util.go",
			"package util\n\nfunc Format() string { return \"formatted\" }\n",
		).
		File(
			"superfluous.go",
			"package example\n\nimport helper \"testmodule/pkg/helper\"\n\nfunc UseHelper() string {\n\treturn helper.Value()\n}\n",
		).
		File(
			"unnecessary_rename.go",
			"package example\n\nimport h \"testmodule/pkg/helper\"\n\nfunc UseRenamed() string {\n\treturn h.Value()\n}\n",
		).
		File(
			"collision.go",
			"package example\n\nimport h \"testmodule/pkg/helper\"\n\nfunc UseCollision() string {\n\thelper := \"local\"\n\n\treturn helper + h.Value()\n}\n",
		).
		File(
			"import_collision.go",
			"package example\n\nimport (\n\th \"testmodule/pkg/helper\"\n\t\"testmodule/pkg/other/helper\"\n)\n\nfunc UseBoth() string {\n\treturn h.Value() + helper.Extra()\n}\n",
		).
		File(
			constant.GeneratedFile,
			"// Code generated by tool DO NOT EDIT.\n\npackage example\n\nimport h \"testmodule/pkg/helper\"\n\nfunc Generated() string {\n\treturn h.Value()\n}\n",
		).
		File(
			"different_name.go",
			"package example\n\nimport u \"testmodule/pkg/util-stuff\"\n\nfunc UseDifferent() string {\n\treturn u.Format()\n}\n",
		).
		File(
			"blank_import.go",
			"package example\n\nimport _ \"testmodule/pkg/helper\"\n\nfunc BlankImport() {}\n",
		).
		File(
			"pkg/alfa/constant/constant.go",
			"package constant\n\nfunc One() string { return \"one\" }\n",
		).
		File(
			"pkg/bravo/constant/constant.go",
			"package constant\n\nfunc Two() string { return \"two\" }\n",
		).
		File(
			"multiple_same_name.go",
			"package example\n\nimport (\n\ta \"testmodule/pkg/alfa/constant\"\n\tb \"testmodule/pkg/bravo/constant\"\n)\n\nfunc UseMultiple() string {\n\treturn a.One() + b.Two()\n}\n",
		).
		File(
			"struct_field.go",
			"package example\n\nimport h \"testmodule/pkg/helper\"\n\ntype Thing struct {\n\thelper string\n}\n\nfunc UseThing() string {\n\treturn h.Value()\n}\n",
		).
		File(
			"pkg/setting/string/string.go",
			"package string\n\nfunc Value(name string) string { return name }\n",
		).
		File(
			"builtin_collision.go",
			"package example\n\nimport model \"testmodule/pkg/setting/string\"\n\nfunc UseBuiltin(name string) string {\n\treturn model.Value(name)\n}\n",
		).
		Directory()
}
