package unit

import (
	"github.com/funtimecoding/soil/pkg/assert"
	"github.com/funtimecoding/soil/pkg/constant"
	"github.com/funtimecoding/soil/pkg/lint/analyzer/testutil"
	"github.com/funtimecoding/soil/pkg/lint/output"
	"github.com/funtimecoding/soil/pkg/tool/gofix"
	"github.com/funtimecoding/soil/pkg/tool/gofix/unit/module_tester"
	"path/filepath"
	"testing"
)

func TestFix(t *testing.T) {
	directory := module_tester.Fix(t)
	r := output.NewResultsWithDirectory(directory)
	all, fileSet := gofix.Load(directory, []string{"./..."})
	violations := gofix.FindViolations(all)
	edits := gofix.BuildAllEdits(fileSet, all, violations, r)
	gofix.ApplyEdits(fileSet, edits, directory, false)
	loadedFiles := gofix.BuildLoadedFiles(all)
	gofix.FixUnloadedReferences(violations, loadedFiles, directory, r)
	t.Run(
		"CrossPackageRename",
		func(t *testing.T) {
			assert.String(
				t,
				"package types\n\nfunc DirectoryPath() string { return directoryName }\n",
				testutil.ReadFile(
					t,
					filepath.Join(
						directory,
						"pkg",
						"types",
						"directory_path.go",
					),
				),
			)
			assert.String(
				t,
				"package types\n\nvar directoryName = \"test\"\n",
				testutil.ReadFile(
					t,
					filepath.Join(
						directory,
						"pkg",
						"types",
						"directory_name.go",
					),
				),
			)
			assert.String(
				t,
				"package types\n\nconst StrayConstant = \"value\"\n",
				testutil.ReadFile(
					t,
					filepath.Join(directory, "pkg", "types", "stray_const.go"),
				),
			)
			assert.String(
				t,
				"package consumer\n\nimport \"testmodule/pkg/types\"\n\nfunc Example() string {\n\t_ = types.StrayConstant\n\n\treturn types.DirectoryPath()\n}\n",
				testutil.ReadFile(
					t,
					filepath.Join(directory, "pkg", "consumer", "use.go"),
				),
			)
		},
	)
	t.Run(
		"SkipsInterfaceMethod",
		func(t *testing.T) {
			assert.String(
				t,
				"package impl\n\nimport \"testmodule/pkg/face\"\n\ntype Server struct{}\n\nfunc (s Server) Addr() string { return \"\" }\n\nvar _ face.Worker = Server{}\n",
				testutil.ReadFile(
					t,
					filepath.Join(directory, "pkg", "impl", "impl.go"),
				),
			)
		},
	)
	t.Run(
		"SkipsGeneratedFile",
		func(t *testing.T) {
			assert.String(
				t,
				"package types\n\n// Code generated by tool DO NOT EDIT.\n\ntype ParamError struct{}\n",
				testutil.ReadFile(
					t,
					filepath.Join(
						directory,
						"pkg",
						"types",
						constant.GeneratedFile,
					),
				),
			)
		},
	)
	t.Run(
		"StructFieldGetsMultiCharacter",
		func(t *testing.T) {
			assert.String(
				t,
				"package fields\n\ntype Entry struct {\n\tReference string\n}\n",
				testutil.ReadFile(
					t,
					filepath.Join(directory, "pkg", "fields", "entry.go"),
				),
			)
		},
	)
	t.Run(
		"MultiSegmentPrefersMultiCharacter",
		func(t *testing.T) {
			assert.String(
				t,
				"package multi\n\nfunc Example() string {\n\tfooReference := \"x\"\n\n\treturn fooReference\n}\n",
				testutil.ReadFile(
					t,
					filepath.Join(directory, "pkg", "multi", "example.go"),
				),
			)
		},
	)
	t.Run(
		"SingleLetterCollisionFallback",
		func(t *testing.T) {
			assert.String(
				t,
				"package collision\n\nfunc Example() string {\n\tr := \"taken\"\n\te := \"test\"\n\n\treturn r + e\n}\n",
				testutil.ReadFile(
					t,
					filepath.Join(directory, "pkg", "collision", "example.go"),
				),
			)
		},
	)
	t.Run(
		"CollisionFallback",
		func(t *testing.T) {
			assert.String(
				t,
				"package abort\n\nfunc Example() string {\n\tt := \"taken\"\n\ta := \"test\"\n\n\treturn t + a\n}\n",
				testutil.ReadFile(
					t,
					filepath.Join(directory, "pkg", "abort", "example.go"),
				),
			)
		},
	)
	t.Run(
		"InnerScopeShadow",
		func(t *testing.T) {
			assert.String(
				t,
				"package shadow\n\nfunc Example() string {\n\tm := map[string]string{\"k\": \"x\"}\n\n\tfor _, a := range m {\n\t\tv := a\n\t\t_ = v\n\t}\n\n\treturn \"\"\n}\n",
				testutil.ReadFile(
					t,
					filepath.Join(directory, "pkg", "shadow", "example.go"),
				),
			)
		},
	)
	t.Run(
		"ParentScopeShadow",
		func(t *testing.T) {
			assert.String(
				t,
				"package parent\n\nfunc Example() {\n\ts := \"status\"\n\tsources := []string{\"a\"}\n\n\tfor _, o := range sources {\n\t\t_ = s + o\n\t}\n}\n",
				testutil.ReadFile(
					t,
					filepath.Join(directory, "pkg", "parent", "example.go"),
				),
			)
		},
	)
	t.Run(
		"ErrorChainSecond",
		func(t *testing.T) {
			assert.String(
				t,
				"package errs\n\nimport \"fmt\"\n\nfunc Example() {\n\te := fmt.Errorf(\"first\")\n\tf := fmt.Errorf(\"second\")\n\t_ = e\n\t_ = f\n}\n",
				testutil.ReadFile(
					t,
					filepath.Join(directory, "pkg", "errs", "example.go"),
				),
			)
		},
	)
	t.Run(
		"ErrorChainThird",
		func(t *testing.T) {
			assert.String(
				t,
				"package errs\n\nimport \"fmt\"\n\nfunc Triple() {\n\te := fmt.Errorf(\"first\")\n\tf := fmt.Errorf(\"second\")\n\tg := fmt.Errorf(\"third\")\n\t_ = e\n\t_ = f\n\t_ = g\n}\n",
				testutil.ReadFile(
					t,
					filepath.Join(directory, "pkg", "errs", "triple.go"),
				),
			)
		},
	)
	t.Run(
		"ExportedCrossPackageRename",
		func(t *testing.T) {
			assert.String(
				t,
				"package sentinel\n\nimport \"fmt\"\n\nvar ErrorQuit = fmt.Errorf(\"quit\")\n",
				testutil.ReadFile(
					t,
					filepath.Join(directory, "pkg", "sentinel", "sentinel.go"),
				),
			)
			assert.String(
				t,
				"package caller\n\nimport (\n\t\"errors\"\n\t\"testmodule/pkg/sentinel\"\n)\n\nfunc Check(e error) bool {\n\treturn errors.Is(e, sentinel.ErrorQuit)\n}\n",
				testutil.ReadFile(
					t,
					filepath.Join(directory, "pkg", "caller", "caller.go"),
				),
			)
			assert.String(
				t,
				"//go:build ignore\n\npackage tagged\n\nimport (\n\t\"errors\"\n\t\"testmodule/pkg/sentinel\"\n)\n\nfunc Handle(e error) bool {\n\treturn errors.Is(e, sentinel.ErrorQuit)\n}\n",
				testutil.ReadFile(
					t,
					filepath.Join(directory, "pkg", "tagged", "tagged.go"),
				),
			)
		},
	)
	t.Run(
		"ResultEntries",
		func(t *testing.T) {
			applied := filterApplied(r.Entries)
			assertResult(
				t,
				applied,
				"pkg/types/directory_path.go",
				"renamed DirPath → DirectoryPath (2 references)",
			)
			assertResult(
				t,
				applied,
				"pkg/types/directory_name.go",
				"renamed dirName → directoryName (2 references)",
			)
			assertResult(
				t,
				applied,
				"pkg/types/stray_const.go",
				"renamed StrayConst → StrayConstant (2 references)",
			)
			assertResult(
				t,
				applied,
				"pkg/sentinel/sentinel.go",
				"renamed ErrQuit → ErrorQuit (2 references)",
			)
			assertResult(
				t,
				applied,
				"pkg/tagged/tagged.go",
				"renamed ErrQuit → ErrorQuit (unloaded)",
			)
		},
	)
}
