package gonetbox

import (
	"github.com/funtimecoding/soil/pkg/argument"
	"github.com/funtimecoding/soil/pkg/errors"
	"github.com/funtimecoding/soil/pkg/instrument"
	"github.com/funtimecoding/soil/pkg/terminal"
	"github.com/funtimecoding/soil/pkg/tool/gonetbox/constant"
	"github.com/funtimecoding/soil/pkg/tool/gonetboxd/client"
	"github.com/spf13/cobra"
)

func Main() {
	s := instrument.NewCommandLine(constant.Identity)
	defer func() { s.Flush(recover()) }()
	t := terminal.New(s)
	c := client.NewEnvironment()
	o := &cobra.Command{
		Use:   constant.Identity.Usage(),
		Short: constant.Identity.Description(),
	}
	o.AddCommand(listDevices(c, t))
	o.AddCommand(getDevice(c, t))
	o.AddCommand(getVirtualMachine(c, t))
	o.AddCommand(listInterfaces(c, t))
	o.AddCommand(listAddresses(c, t))
	o.AddCommand(listVirtualInterfaces(c, t))
	o.AddCommand(listVirtualAddresses(c, t))
	o.AddCommand(listVirtualDisks(c, t))
	o.AddCommand(createVirtualDisk(c, t))
	o.AddCommand(renameDevice(c, t))
	o.AddCommand(renameVirtualMachine(c, t))
	o.AddCommand(setDevicePrimaryAddress(c, t))
	o.AddCommand(setVirtualPrimaryAddress(c, t))
	o.AddCommand(updateDevice(c, t))
	o.AddCommand(updateVirtualMachine(c, t))
	o.AddCommand(listAddressRanges(c, t))
	o.AddCommand(createAddressRange(c, t))
	o.AddCommand(listLocations(c, t))
	o.AddCommand(createLocation(c, t))
	o.AddCommand(listPlatforms(c, t))
	o.AddCommand(createPlatform(c, t))
	o.AddCommand(listWirelessNetworks(c, t))
	o.AddCommand(createWirelessNetwork(c, t))
	o.AddCommand(listSites(c, t))
	o.AddCommand(listTenants(c, t))
	o.AddCommand(listDeviceRoles(c, t))
	o.AddCommand(listManufacturers(c, t))
	o.AddCommand(listDeviceTypes(c, t))
	o.AddCommand(createSite(c, t))
	o.AddCommand(createTenant(c, t))
	o.AddCommand(createDeviceRole(c, t))
	o.AddCommand(createManufacturer(c, t))
	o.AddCommand(createDeviceType(c, t))
	o.AddCommand(createDevice(c, t))
	o.AddCommand(createInterface(c, t))
	o.AddCommand(setInterfacePhysicalAddress(c, t))
	o.AddCommand(setVirtualInterfacePhysicalAddress(c, t))
	o.AddCommand(createAddress(c, t))
	o.AddCommand(listClusterTypes(c, t))
	o.AddCommand(listClusters(c, t))
	o.AddCommand(listVirtualMachines(c, t))
	o.AddCommand(createClusterType(c, t))
	o.AddCommand(createCluster(c, t))
	o.AddCommand(createVirtualMachine(c, t))
	o.AddCommand(createVirtualInterface(c, t))
	o.AddCommand(createVirtualAddress(c, t))
	o.AddCommand(listTags(c, t))
	o.AddCommand(createTag(c, t))
	o.AddCommand(addDeviceTag(c, t))
	o.AddCommand(removeDeviceTag(c, t))
	o.AddCommand(addVirtualTag(c, t))
	o.AddCommand(removeVirtualTag(c, t))
	o.AddCommand(addDeviceJournalEntry(c, t))
	o.AddCommand(listDeviceJournalEntries(c, t))
	o.AddCommand(addVirtualJournalEntry(c, t))
	o.AddCommand(listVirtualJournalEntries(c, t))
	o.AddCommand(updateJournalEntry(c, t))
	o.AddCommand(deleteJournalEntry(c, t))
	o.AddCommand(deleteAddress(c, t))
	o.AddCommand(setDeviceLabel(c, t))
	o.AddCommand(removeDeviceLabel(c, t))
	o.AddCommand(listDeviceLabels(c, t))
	o.AddCommand(setVirtualLabel(c, t))
	o.AddCommand(removeVirtualLabel(c, t))
	o.AddCommand(listVirtualLabels(c, t))
	o.AddCommand(listTunnelGroups(c, t))
	o.AddCommand(listTunnels(c, t))
	o.AddCommand(listTunnelTerminations(c, t))
	o.AddCommand(createTunnelGroup(c, t))
	o.AddCommand(createTunnel(c, t))
	o.AddCommand(createDeviceTunnelTermination(c, t))
	o.AddCommand(createVirtualTunnelTermination(c, t))
	o.AddCommand(listPrefixes(c, t))
	o.AddCommand(createPrefix(c, t))
	o.AddCommand(listCables(c, t))
	o.AddCommand(createCable(c, t))
	argument.CobraInstrument(o, s)
	argument.CobraStamp(o, constant.Identity)
	errors.PanicOnError(o.Execute())
}
