package unit

import (
	"github.com/funtimecoding/soil/pkg/argument/constant"
	"github.com/funtimecoding/soil/pkg/assert"
	"testing"
)

func TestConstant(t *testing.T) {
	assert.String(t, "arm", constant.Arm)
	assert.String(t, "bulk", constant.Bulk)
	assert.String(t, "cluster", constant.Cluster)
	assert.String(t, "container", constant.Container)
	assert.String(t, "context", constant.Context)
	assert.String(t, "core", constant.Core)
	assert.String(t, "dense", constant.Dense)
	assert.String(t, "disk", constant.Disk)
	assert.String(t, "download", constant.Download)
	assert.String(t, "end", constant.End)
	assert.String(t, "file", constant.File)
	assert.String(t, "group", constant.Group)
	assert.String(t, "hardware", constant.Hardware)
	assert.String(t, "information", constant.Information)
	assert.String(t, "interactive", constant.Interactive)
	assert.String(t, "investigate", constant.Investigate)
	assert.String(t, "issue", constant.Issue)
	assert.String(t, "key", constant.Key)
	assert.String(t, "log", constant.Log)
	assert.String(t, "loop", constant.Loop)
	assert.String(t, "maintainer-mail", constant.MaintainerMail)
	assert.String(t, "maintainer-name", constant.MaintainerName)
	assert.String(t, "memory", constant.Memory)
	assert.String(t, "message", constant.Message)
	assert.String(t, "migrate", constant.Migrate)
	assert.String(t, "mine", constant.Mine)
	assert.String(t, "name", constant.Name)
	assert.String(t, "node", constant.Node)
	assert.String(t, "old", constant.Old)
	assert.String(t, "on-upgrade", constant.OnUpgrade)
	assert.String(t, "package", constant.Package)
	assert.String(t, "parent", constant.Parent)
	assert.String(t, "password", constant.Password)
	assert.String(t, "pod", constant.Pod)
	assert.String(t, "pretend", constant.Pretend)
	assert.String(t, "reset", constant.Reset)
	assert.String(t, "retry", constant.Retry)
	assert.String(t, "run", constant.Run)
	assert.String(t, "runbook", constant.Runbook)
	assert.String(t, "schedule", constant.Schedule)
	assert.String(t, "source", constant.Source)
	assert.String(t, "space", constant.Space)
	assert.String(t, "statistic", constant.Statistic)
	assert.String(t, "summary", constant.Summary)
	assert.String(t, "systemd-unit", constant.SystemdUnit)
	assert.String(t, "team", constant.Team)
	assert.String(t, "title", constant.Title)
	assert.String(t, "topic", constant.Topic)
	assert.String(t, "unit", constant.Unit)
	assert.String(t, "unknown", constant.Unknown)
}
