package constant

const (
	TagAge         = "age"
	TagAssignee    = "assignee"
	TagCategory    = "category"
	TagChanges     = "changes"
	TagCluster     = "cluster"
	TagComment     = "comment"
	TagConcerns    = "concerns"
	TagCopyable    = "copyable"
	TagDense       = "dense"
	TagDescription = "description"
	TagEmoji       = "emoji"
	TagFilter      = "filter"
	TagFingerprint = "fingerprint"
	TagGraph       = "graph"
	TagHost        = "host"
	TagIdentifier  = "identifier"
	TagInstance    = "instance"
	TagInvestigate = "investigate"
	TagKey         = "key"
	TagLabels      = "labels"
	TagMarkdown    = "markdown"
	TagName        = "name"
	TagProject     = "project"
	TagRunbook     = "runbook"
	TagScore       = "score"
	TagState       = "state"
	TagStatus      = "status"
	TagTimestamp   = "timestamp"
	TagType        = "type"
	TagUsage       = "usage"
	TagWiki        = "wiki"
)
